apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: valuestream
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: valuestream-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: HOST
          value: "0.0.0.0"
        - name: ADMIN_SECRET
          valueFrom:
            secretKeyRef:
              name: valuestream-secrets
              key: ADMIN_SECRET
        # Add proxy configuration environments if SOCKS proxy is used in K8s
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: backend
